version: 1.9.4.{build}
image:
  - Visual Studio 2022
  - Ubuntu
  - macOS
  - macOS-Monterey
  - macOS-Bigsur
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore src/Vlingo.Xoom.Http.sln
build:
  project: src/Vlingo.Xoom.Http.sln
  verbosity: minimal
  publish_nuget: true
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    before_test:
      - netsh advfirewall set currentprofile state off
    after_test:
      - netsh advfirewall set  currentprofile state on
test_script:
- dotnet test src/Vlingo.Xoom.Http.Tests
deploy:
- provider: NuGet
  api_key:
    secure: 4VJZEFZNaDrk3FJmRSmBW+wQugDoPi6DtVlsLZ+26IOo+wb0u9JlnTOTQF+NXs2s
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/37621a855e91c31ab1da
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
